### ISSUE TITLE
hard defines for read/write/select/open/close also affects other files

### ISSUE THREAD

**Issue by Apollon77** [ChristianVisintin/termiWin#1]
Hey,

I currently try to get libmbus to compile on windows and sofound your great termiWin as replacement for termios.h ...
Bute when I use this the redefines for "read/write/select/open/close" in termiWin.h also affects other methods called "open/close" in a complete different file (definition of a struct in libmbus) ends up in weired error messages.

Here is the struct from libmbus:
https://github.com/Apollon77/libmbus/blob/build-windows/mbus/mbus-protocol-aux.h#L92

and this generates error ;

..\libmbus\mbus\mbus-protocol-aux.c(1529): error C2039: 'openSerial': is not a member of '_mbus_handle'

as soon as the code wants to assign to "open" property:
https://github.com/Apollon77/libmbus/blob/build-windows/mbus/mbus-protocol-aux.c#L1529

Is there any way to solve this?!

Ingo

**Comment by Apollon77** [comment]
It seems I was able to fix this by moving the defines into the termiWin.c File instead of the .h file ... 

For me it was result of "Google" and "try and error".

Makes this sense?

**Comment by veeso** [comment]
Hi,
I'm glad my library has been useful for you!  
Well, if those definitions create conflicts with another library, it's ok to delete them from the header file (but it's not necessary to put them in the C files then).

**Comment by Apollon77** [comment]
Ok, thank you ... I was able to compile after many things ... my tests only use tcp but it's not working there :-( serial I need to test later somehow

**Comment by veeso** [comment]
I added to the library the possibility to disable the hard definitions of close/open/select etc, just defining TERMIWIN_DONOTREDEFINE in your project.
Thank you for reporting it!
