### ISSUE TITLE
How to Cross-compile it with mingw-w64 from Linux system

### ISSUE THREAD

**Issue by Droid-MAX** [ChristianVisintin/termiWin#10]

**Comment by veeso** [comment]
Hi,

I don't know actually, since I've never done cross-compilation with mingw.
you can try with cmake:

```sh
# You must be in the project root
cmake .. -G "MinGW Makefiles" -DTERMIWIN_DONOTREDEFINE=yes -DCMAKE_SH="CMAKE_SH-NOTFOUND"
mingw64-make
```

If it doesn't work I don't know how to help you.

**Comment by Droid-MAX** [comment]
In fact, the cause of the matter is like this.
I am adapting some software projects to the Windows platform, but found some problems during the cross-compilation process. Some source files include termios.h header file, but mingw-w64 does not have this file, so I analyze the problem from another perspective  , I found that the serial-related function code of the flashrom software project may help me solve the adaptation problem, but I still haven’t fully understood the related functional logic of flashrom. 
I am not going to use termiwin to solve the problem of missing header files, but I am very grateful for your reply, thank you! 
If you are interested in my adaptation work, here is the URL of the related project.

[spi-nand-prog](https://github.com/Droid-MAX/spi-nand-prog)

[iceprog-serprog](https://github.com/Droid-MAX/iceprog-serprog)

**Comment by Droid-MAX** [comment]
https://github.com/dmsc/iceprog-serprog/issues/1
