### ISSUE TITLE
Missing defines CREAD, CLOCAL and B600

### ISSUE THREAD

**Issue by Apollon77** [ChristianVisintin/termiWin#2]
I currently try to get libmbus to compile on windows and use your termiWin.

I miss:
- B600 ... ok this one was easy to add :-)
- CREAD
- CLOCAL

Do you have any idea how to add them?

**Comment by veeso** [comment]
For B600 it's enough to add  
`C
#define B600 CBR_600 
`
as you probably did (I'll update the library adding the missing baud rates).

For the other two options, just give me a few days to find out (sorry, I'm kinda busy with the job), you could try to define them in the header file and check if it works anyway in the meantime.

**Comment by Apollon77** [comment]
Yes I defined B600 as you showed :-)

The others I defined as 0x00000000 for now, so it compiles.

Currently I try to get libmbus tcp working first because I already have tests for this. Serial is more complicated to test, so second step

**Comment by veeso** [comment]
I've updated the library adding those missing options. I've searched for an implementation of CLOCAL and CREAD in Windows but I couldn't find anything, so I just defined them as you did (0x00000000).

**Comment by Apollon77** [comment]
ok, as thought ... :-)
