### ISSUE TITLE
Control/Charset option handling is not working

### ISSUE THREAD

**Issue by Apollon77** [ChristianVisintin/termiWin#4]
I struggled around a very long time now, and finally noted that the "getCharSet" and "getControlOptions" methods are not working and return crap (or better: only 0").

Because of this wrong options are set.

My cflag is sset as follows:
```
memset(term, 0, sizeof(*term));
    term->c_cflag |= (CS8/*|CREAD|CLOCAL*/);
    term->c_cflag |= PARENB;
```

resulting in 

```
c_cflag = 4c00
```

This struct is then used to call
```
 tcsetattr(handle->fd, TCSANOW, term);
```

Now after nothing worked I added debug and I found out that the"getByte" calls (at least) in getCharSet and getControlOptions return 0 in this case, leading to wrong results.

Could you please check that?!
I will also try to get in the bianry comare stuff, but ... maybe your are faster :-)

Thank you for all your support!

**Comment by Apollon77** [comment]
Looked into it. Calls need to be 1,1 and 1,0. with 5 he would shift 8*5=40 times ... can not work.

**Comment by Apollon77** [comment]
verified.

getControlOptions needs to be
```
	int byte = getByte(flag,1,0);
```

and getCharSetneeds to be 

```
	int byte = getByte(flag,1,1);
```

to get the correct values. With this it works great!

I did not checked the other three "get...Options" methods, but expoect comparable problems there.

**Comment by veeso** [comment]
Thank you,
this will be fixed
