### ISSUE TITLE
Tons of Errors

### ISSUE THREAD

**Issue by uruskan** [ChristianVisintin/termiWin#9]
A:\Projects\cProjects>gcc -c termiWin.c
termiWin.h:39:14: error: conflicting types for 'openSerial'
 #define open openSerial
              ^~~~~~~~~~
termiWin.h:180:5: note: previous declaration of 'openSerial' was here
 int openSerial(char* portname, int opt);
     ^~~~~~~~~~
termiWin.h:36:14: error: conflicting types for 'readFromSerial'
 #define read readFromSerial
              ^~~~~~~~~~~~~~
termiWin.h:178:5: note: previous declaration of 'readFromSerial' was here
 int readFromSerial(int fd, char* buffer, int count);
     ^~~~~~~~~~~~~~
termiWin.h:37:15: error: conflicting types for 'writeToSerial'
 #define write writeToSerial
               ^~~~~~~~~~~~~
termiWin.h:179:5: note: previous declaration of 'writeToSerial' was here
 int writeToSerial(int fd, char* buffer, int count);
     ^~~~~~~~~~~~~
termiWin.c: In function 'readFromSerial':
termiWin.c:454:44: warning: passing argument 4 of 'ReadFile' from incompatible pointer type [-Wincompatible-pointer-types]
   ret = ReadFile(com.hComm, buffer, count, &rc, NULL);
                                            ^~~
In file included from C:/Mingw-w64/mingw64/x86_64-w64-mingw32/include/winbase.h:18,
                 from C:/Mingw-w64/mingw64/x86_64-w64-mingw32/include/windows.h:70,
                 from termiWin.h:29:
C:/Mingw-w64/mingw64/x86_64-w64-mingw32/include/fileapi.h:167:106: note: expected 'LPDWORD' {aka 'long unsigned int *'} but argument is of type 'int *'
   WINBASEAPI WINBOOL WINAPI ReadFile (HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
                                                                                                  ~~~~~~~~^~~~~~~~~~~~~~~~~~~
termiWin.c: In function 'writeToSerial':
termiWin.c:468:45: warning: passing argument 4 of 'WriteFile' from incompatible pointer type [-Wincompatible-pointer-types]
   ret = WriteFile(com.hComm, buffer, count, &rc, NULL);
                                             ^~~
In file included from C:/Mingw-w64/mingw64/x86_64-w64-mingw32/include/winbase.h:18,
                 from C:/Mingw-w64/mingw64/x86_64-w64-mingw32/include/windows.h:70,
                 from termiWin.h:29:
C:/Mingw-w64/mingw64/x86_64-w64-mingw32/include/fileapi.h:175:109: note: expected 'LPDWORD' {aka 'long unsigned int *'} but argument is of type 'int *'
   WINBASEAPI WINBOOL WINAPI WriteFile (HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
                                                                                                     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
termiWin.c: In function 'openSerial':
termiWin.c:483:5: warning: 'strncat' specified bound 4 equals source length [-Wstringop-overflow=]
     strncat(com.port, "\\\\.\\", strlen("\\\\.\\"));

**Comment by veeso** [comment]
For the redeclaration problem try defining TERMIWIN_DONOTREDEFINE in your build defines.

```sh
gcc ... -D TERMIWIN_DONOTREDEFINE
```

For the other problems I don't know actually, I've never tried to build termiWin with MinGW, but only with MSVC: I'll try when I've got some time, but I think there are some compatibility issues with MinGW library.

**Comment by uruskan** [comment]
I commented out the defining lines and it compiled as same as with the -D TERMIWIN_DONOTREDEFINE command. But my project isn't working anyway. I never tried to compile it with MSVC will try it. The project I am trying to port to windows is this one btw: https://raw.githubusercontent.com/mevdschee/peg-solitaire.c/master/peg-solitaire.c
Thank you for your help.

**Comment by veeso** [comment]
I've just tried building peg-solitaire with MinGW.

- I replaced termios.h with termiWin.h in the source code.
- I replaced hthe select function with select_something else in the source code (rows 92, 357).
- I build with gcc peg-solitaire.c termiWin.c -I . -o peg-solitaire -D TERMIWIN_DONOTREDEFINE and it works fine

I've got MinGW with GCC 8.2.0 on Windows 10 (with latest updates).
If you have the WSL it works fine there, otherwise you could try as I said with MSVC, but I cannot guarantee it's gonna work.

**Comment by uruskan** [comment]
I did the exact steps before ur comment, it compiles but the program doesn't work. I tried with MSVC but there are some problems too (not from termiwin). Anyway thanks for your time trying to help such not important thing.
